### PR TITLE
Remove button

### PR DESCRIPTION
**Pull request by Beh5611**
Added a remove button to the Dashboard.js file.

This required a new event function to be made. In the eventHandler.js you will see a new func called "handleDeleteIndicator".

There was a specific bug produced that I took note of in the google doc that I was unable to resolve. Its not really a big deal so I left it be for now.

### CODE REVIEW

**Comment by Vladmidir** [comment]
I think that it is a good idea to fix the compare indicators bug in this pr. I believe that the state u need to set after removing an indicator is `currentSelectedMultiIndicators`. Or, actually, that state is a list of indicators currently selected. Make sure that you are also updating `selectedIndicators` correctly (I assume that you do, just thinking outloud here). The `currentSelectedMultiIndicators` is a list of indicators selected for comparison.

**Comment by Vladmidir** [comment]
Also, please include screenshots if there are UI changes.

**Comment by Beh5611** [comment]
The bug was fixed, and as requested I will include a picture of the UI change in the doc.

**Comment by Vladmidir** [comment]
Looks good.

**Pull request merged**
